
### 获取全部项目
GET http://localhost:4000/api/project HTTP/1.1
content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOWRkZDA1MjY3ZjQ3ODY3ZDhhMWNiZSIsInBhc3N3b3JkIjoiJDJhJDEwJGRHUi9SNUtJWFYxZTVqQi53UGRWd3V5bXFIMWdSaDJuZ3htZ3hoQ0IzL3JrQTh5MVlpUS91IiwiaWF0IjoxNTUzODUwNDYxLCJleHAiOjE1NTM4NTc2NjF9.YCjQoBap9ND_Bc4Fd5kvcq05-7fZ8BcOYgylX3ZSNPA







### 获取项目详情
GET http://localhost:4000/api/project/5c9db04c8f6828764bc907d9 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOWRkZDA1MjY3ZjQ3ODY3ZDhhMWNiZSIsInBhc3N3b3JkIjoiJDJhJDEwJGRHUi9SNUtJWFYxZTVqQi53UGRWd3V5bXFIMWdSaDJuZ3htZ3hoQ0IzL3JrQTh5MVlpUS91IiwiaWF0IjoxNTUzODUwNDYxLCJleHAiOjE1NTM4NTc2NjF9.YCjQoBap9ND_Bc4Fd5kvcq05-7fZ8BcOYgylX3ZSNPA








### 创建项目
POST http://localhost:4000/api/project HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOWRkZDA1MjY3ZjQ3ODY3ZDhhMWNiZSIsInBhc3N3b3JkIjoiJDJhJDEwJGRHUi9SNUtJWFYxZTVqQi53UGRWd3V5bXFIMWdSaDJuZ3htZ3hoQ0IzL3JrQTh5MVlpUS91IiwiaWF0IjoxNTUzODUwNDYxLCJleHAiOjE1NTM4NTc2NjF9.YCjQoBap9ND_Bc4Fd5kvcq05-7fZ8BcOYgylX3ZSNPA

{
  "title": "post创建项目1",
  "desc": "post创建项目desc",
  "skills": "1,2,3",
  "cycle": "30",
  "price": "3000"
}








### 项目评论
PATCH http://localhost:4000/api/project/5c9ddda2d0c96d87459962ce HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOWRkZDA1MjY3ZjQ3ODY3ZDhhMWNiZSIsInBhc3N3b3JkIjoiJDJhJDEwJGRHUi9SNUtJWFYxZTVqQi53UGRWd3V5bXFIMWdSaDJuZ3htZ3hoQ0IzL3JrQTh5MVlpUS91IiwiaWF0IjoxNTUzODUwNDYxLCJleHAiOjE1NTM4NTc2NjF9.YCjQoBap9ND_Bc4Fd5kvcq05-7fZ8BcOYgylX3ZSNPA

{
  "content": "第2条评论"
}





### 项目更新
PATCH http://localhost:4000/api/project/5c9db04c8f6828764bc907d9 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOWRkZDA1MjY3ZjQ3ODY3ZDhhMWNiZSIsInBhc3N3b3JkIjoiJDJhJDEwJGRHUi9SNUtJWFYxZTVqQi53UGRWd3V5bXFIMWdSaDJuZ3htZ3hoQ0IzL3JrQTh5MVlpUS91IiwiaWF0IjoxNTUzODUwNDYxLCJleHAiOjE1NTM4NTc2NjF9.YCjQoBap9ND_Bc4Fd5kvcq05-7fZ8BcOYgylX3ZSNPA

{
  "title": "更新后的项目信息",
  "dev_user": {
    "role": 3,
    "email": "dev1@ph.com",
    "password": "123123",
    "profile": {
      "phone": "17864387607",
      "name": "dev1",
      "avatar": "https://ws1.sinaimg.cn/large/006djfE8ly1g0u1e1lzxwj30ig0igq3o.jpg",
      "desc": "dev"
    },
    "skill": "",
    "msgs": []
  }
}





### 删除项目
DELETE http://localhost:4000/api/project/5c9d8758afe0327312b5ea3b HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOWRkZDA1MjY3ZjQ3ODY3ZDhhMWNiZSIsInBhc3N3b3JkIjoiJDJhJDEwJGRHUi9SNUtJWFYxZTVqQi53UGRWd3V5bXFIMWdSaDJuZ3htZ3hoQ0IzL3JrQTh5MVlpUS91IiwiaWF0IjoxNTUzODUwNDYxLCJleHAiOjE1NTM4NTc2NjF9.YCjQoBap9ND_Bc4Fd5kvcq05-7fZ8BcOYgylX3ZSNPA
