
### 获取全部项目
GET http://localhost:4000/api/project HTTP/1.1
content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOWNiMzE3YjJiY2I4NjZhMzE2ZTYzZCIsInBhc3N3b3JkIjoiJDJhJDEwJEhuUi5ZZTIvaGVSdDU3VC9jZC9ERC52NW43eFh5MFo0SjViUFp5Y2o5Vm9YeUtOMDJ6Li8yIiwiaWF0IjoxNTUzODI0Mzg2LCJleHAiOjE1NTM4Mjc5ODZ9.oWJfVij7VJC43NHMQuJXLu1RDI2drYHa2GxDSxAyOeU







### 获取项目详情
GET http://localhost:4000/api/project/5c9d786fe0c1ff9863a524d3 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOWNiMzE3YjJiY2I4NjZhMzE2ZTYzZCIsInBhc3N3b3JkIjoiJDJhJDEwJEhuUi5ZZTIvaGVSdDU3VC9jZC9ERC52NW43eFh5MFo0SjViUFp5Y2o5Vm9YeUtOMDJ6Li8yIiwiaWF0IjoxNTUzODI0Mzg2LCJleHAiOjE1NTM4Mjc5ODZ9.oWJfVij7VJC43NHMQuJXLu1RDI2drYHa2GxDSxAyOeU








### 创建项目
POST http://localhost:4000/api/project HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOWNiMzE3YjJiY2I4NjZhMzE2ZTYzZCIsInBhc3N3b3JkIjoiJDJhJDEwJEhuUi5ZZTIvaGVSdDU3VC9jZC9ERC52NW43eFh5MFo0SjViUFp5Y2o5Vm9YeUtOMDJ6Li8yIiwiaWF0IjoxNTUzODI0Mzg2LCJleHAiOjE1NTM4Mjc5ODZ9.oWJfVij7VJC43NHMQuJXLu1RDI2drYHa2GxDSxAyOeU

{
  "title": "post创建项目1",
  "desc": "post创建项目desc",
  "skills": "1,2,3",
  "cycle": "30",
  "price": "3000"
}








### 项目评论
PUT http://localhost:4000/api/project/5c9d786fe0c1ff9863a524d3 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOWNiMzE3YjJiY2I4NjZhMzE2ZTYzZCIsInBhc3N3b3JkIjoiJDJhJDEwJEhuUi5ZZTIvaGVSdDU3VC9jZC9ERC52NW43eFh5MFo0SjViUFp5Y2o5Vm9YeUtOMDJ6Li8yIiwiaWF0IjoxNTUzODI0Mzg2LCJleHAiOjE1NTM4Mjc5ODZ9.oWJfVij7VJC43NHMQuJXLu1RDI2drYHa2GxDSxAyOeU

{
  "newComments": {
    "user": {
      "role": 2,
      "email": "demand1@ph.com",
      "profile": {
        "phone": "17864387607",
        "name": "demand1",
        "avatar": "https://ws1.sinaimg.cn/large/006djfE8ly1g0u1e1lzxwj30ig0igq3o.jpg",
        "desc": "一个想做网站的产品经理"
      },
      "skill": "",
      "msgs": []
    },
    "content": "第一条评论"
  }
}





### 项目更新
PUT http://localhost:4000/api/project/5c9d786fe0c1ff9863a524d3 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOWNiMzE3YjJiY2I4NjZhMzE2ZTYzZCIsInBhc3N3b3JkIjoiJDJhJDEwJEhuUi5ZZTIvaGVSdDU3VC9jZC9ERC52NW43eFh5MFo0SjViUFp5Y2o5Vm9YeUtOMDJ6Li8yIiwiaWF0IjoxNTUzODI0Mzg2LCJleHAiOjE1NTM4Mjc5ODZ9.oWJfVij7VJC43NHMQuJXLu1RDI2drYHa2GxDSxAyOeU

{
  "title": "更新后的项目信息",
  "dev_user": {
    "role": 3,
    "email": "dev1@ph.com",
    "password": "123123",
    "profile": {
      "phone": "17864387607",
      "name": "dev1",
      "avatar": "https://ws1.sinaimg.cn/large/006djfE8ly1g0u1e1lzxwj30ig0igq3o.jpg",
      "desc": "dev"
    },
    "skill": "",
    "msgs": []
  }
}





### 删除项目
DELETE http://localhost:4000/api/project/5c9d8758afe0327312b5ea3b HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOWNiMzE3YjJiY2I4NjZhMzE2ZTYzZCIsInBhc3N3b3JkIjoiJDJhJDEwJEhuUi5ZZTIvaGVSdDU3VC9jZC9ERC52NW43eFh5MFo0SjViUFp5Y2o5Vm9YeUtOMDJ6Li8yIiwiaWF0IjoxNTUzODI0Mzg2LCJleHAiOjE1NTM4Mjc5ODZ9.oWJfVij7VJC43NHMQuJXLu1RDI2drYHa2GxDSxAyOeU
