

### 注册
POST http://localhost:4000/api/user/register HTTP/1.1
content-type: application/json

{
  "email": "demand1@ph.com",
  "password": "123123",
  "password2": "123123",
  "role": 2
}




### 登录
POST http://localhost:4000/api/user/login HTTP/1.1
content-type: application/json

{
  "email": "demand1@ph.com",
  "password": "123123"
}





### 获取当前登录用户信息
GET http://localhost:4000/api/user HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOWRkZDA1MjY3ZjQ3ODY3ZDhhMWNiZSIsInBhc3N3b3JkIjoiJDJhJDEwJGRHUi9SNUtJWFYxZTVqQi53UGRWd3V5bXFIMWdSaDJuZ3htZ3hoQ0IzL3JrQTh5MVlpUS91IiwiaWF0IjoxNTUzODUwNDYxLCJleHAiOjE1NTM4NTc2NjF9.YCjQoBap9ND_Bc4Fd5kvcq05-7fZ8BcOYgylX3ZSNPA




### 获取用户信息
GET http://localhost:4000/api/user/5c9dcb567ad2da8305600397 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOWRkZDA1MjY3ZjQ3ODY3ZDhhMWNiZSIsInBhc3N3b3JkIjoiJDJhJDEwJGRHUi9SNUtJWFYxZTVqQi53UGRWd3V5bXFIMWdSaDJuZ3htZ3hoQ0IzL3JrQTh5MVlpUS91IiwiaWF0IjoxNTUzODUwNDYxLCJleHAiOjE1NTM4NTc2NjF9.YCjQoBap9ND_Bc4Fd5kvcq05-7fZ8BcOYgylX3ZSNPA





### 更新 demand 用户信息
PATCH http://localhost:4000/api/user/5c9cb317b2bcb866a316e63d HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOWRkZDA1MjY3ZjQ3ODY3ZDhhMWNiZSIsInBhc3N3b3JkIjoiJDJhJDEwJGRHUi9SNUtJWFYxZTVqQi53UGRWd3V5bXFIMWdSaDJuZ3htZ3hoQ0IzL3JrQTh5MVlpUS91IiwiaWF0IjoxNTUzODUwNDYxLCJleHAiOjE1NTM4NTc2NjF9.YCjQoBap9ND_Bc4Fd5kvcq05-7fZ8BcOYgylX3ZSNPA

{
  "profile": {
    "name": "demand"
  }
}

